FROM httpd:2.4

COPY local /usr/local/apache2/htdocs/local
COPY ./index.html /usr/local/apache2/htdocs/
COPY ./standalone.js /usr/local/apache2/htdocs/
COPY ./standalone.js.gz /usr/local/apache2/htdocs/
COPY ./standalone.js.map /usr/local/apache2/htdocs/
COPY ./standalone.js.map.gz /usr/local/apache2/htdocs/
